name: Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Ipopt
        run: |
          sudo $GITHUB_WORKSPACE/install.sh
          sudo ldconfig

      - name: Test installation
        run: |
          cd $GITHUB_WORKSPACE/testing
          make -j4
          make test
