name: Docker image

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    env:
      COMPOSE_FILE: .ci/docker-compose.yml
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login - ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify image
        run: |
          docker-compose build
          docker-compose run tests

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/nocoinman/ipopt-cxx-suite:latest